---
title: "Flexdashboard Example"
output: 
  flexdashboard::flex_dashboard:
   theme: united
   runtime : shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(shiny)
library(RWeka)
library(party)
library(DT)
library(gtExtras)
```

Exploratory Data analysis
==============================================================================

Column {.sidebar}
-----------------------------------------------------------------------


```{r}

varSelectInput("Y", "Variable_Y:",iris)


```


```{r}
#selectInput("Y", "Variable_Y:",choices = c("Sepal.Length", "iris$Sepal.Width"), selceted= "Sepal.Length")
```

Column
---------------------------------------------------------------------
```{r}
head(iris) %>%
  gt::gt() %>%
  # reverse = green for low, purple for high
  gt_hulk_col_numeric(Sepal.Length:Petal.Width, reverse = FALSE)
  #gt_hulk_col_numeric(Sepal.Length:Sepal.Width, reverse = FALSE)
  

```


```{r}
renderPlot({
   ggplot(data = iris, aes(x= Species, y= !!input$Y, fill = Species))+
  geom_bar(stat="identity")+
  ggtitle("Count of Species")+
  scale_fill_brewer( palette = "Dark2")
})  
```

Column
-----------------------------------------------------------------
```{r}
ggplot(data = iris, aes(x= Species, y= Petal.Width, color = Species, size = Species))+
  geom_jitter()+
  ggtitle("Count of Species")+
  scale_fill_brewer( palette = "Dark2")
```



```{r}
ggplot(iris, aes(x="", y=Petal.Width , fill=Species)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0)+
  scale_fill_brewer( palette = "Set2")
```

Machine Learning Model
=====================================================================


Column
---------------------------------------------------------------------

```{r}
m1 <- J48(Species~., data = iris)
if(require("party", quietly = TRUE)) plot(m1)

```

```{r}
summary(m1)
```
Column
------------------------------------------------------------------------
```{r}
summary(iris)
```

Summary and Statistics
=============================================================================

Column {.sidebar}
-----------------------------------------------------------------------




Column
---------------------------------------------------------------------------

```{r}
iris %>% 
dplyr::group_by(Species) %>%
  # must end up with list of data for each row in the input dataframe
  dplyr::summarize(Sepal.Length1 = list(Sepal.Length), .groups = "drop") %>%
  gt::gt() %>%
  gt_plt_sparkline(Sepal.Length1)
```
Column
-----------------------------------------------------------------------------

```{r}
   iris %>% 
   #gt::gt() %>%
  #gt_color_rows(Sepal.Length:Petal.Width) %>% 
  dplyr::select(Sepal.Length, Species) %>%
  dplyr::mutate(Sepal.Length_max = round(Sepal.Length/max(Sepal.Length) * 100, digits = 2),
                Sepal.Length_scaled = Sepal.Length/max(Sepal.Length) * 100) %>%
  dplyr::mutate(Sepal.Length_unscaled = Sepal.Length) %>%
  gt::gt() %>%
  gt_plt_bar_pct(column = Sepal.Length_scaled, scaled = TRUE) %>%
  gt_plt_bar_pct(column = Sepal.Length_unscaled, scaled = FALSE, fill = "blue", background = "lightblue") 
 # cols_align("center", contains("scale")) %>%
  ##cols_width(4 ~ px(125),
    #         5 ~ px(125))
 

  
```

